### ISSUE TITLE
Ванильное управление состоянием

### ISSUE THREAD

**Issue by denisSurkov** [denisSurkov/fiit-courses-vizualizator#4]
### Проблема
Мы _не можем_ использовать никакие библиотеки на фронте. Но в то же время нам нужно как-то управлять состоянием приложения. Вызывать коллбэки, когда данные как-то поменялись. 

### Где будем использовать
- Как и на roadmap.sh, у нас можно будет отмечать пройденные блоки. Получается, нам нужно где-то хранить это состояние (пока "состояние" держится только пока страница не перезагружена, в roadmap.sh при перезагрузки страницы отмеченные блоки сохраняются. Это тоже сделаем, но потом);
- Если успеем сделать выбор своего пути (с перетаскиванием блоков), нужно будет подсчитывать зеды в спецкурсах.

### Примерный интерфейс 
> Методов может быть больше. Пока сложно понять, что еще пригодиться.

#### `storage.register(fieldToChange, onFieldChangeCallback)`

Я думаю, что это самый простой способ как-то зарегистрировать обработчик изменения состояния. То есть будет выглядеть примерно так:

```js
func onCompetenceCompleted(competenceId) {
     const elementWithCompentence = competenceToElement[competenceId];
     elementWithCompentence.color = "red";
}


storage.register("complitedCompetence", onCompetenceCompleted);
```

#### `storage.getValue(key)`
Способ достать какое-то значение по ключу

#### `storage.setValue(key, value)`
Способ задать значение по ключу

### Результат задачи

Я бы предложил оформить `storage` в виде класса. В комментариях можно показать, как примерно им пользоваться (без селекторов документа).

**Comment by artemijkurganov** [comment]
Решено в #7
