### ISSUE TITLE
Сделать предподсчеты графа

### ISSUE THREAD

**Issue by denisSurkov** [denisSurkov/fiit-courses-vizualizator#8]
## Ввод

На вход конфиг роадмапа без полезной нагрузки.

```json
[
  {
    "mode": "theme",
    "children": [
      {
        "mode": "module",
      }
    ]
  },
  {
    "mode": "theme",
    "children": [
      {
        "mode": "module",
      },
     {
        "mode": "module",
      }
    ]
  }
]
```

## Вывод

1. Рассчитать для каждого блока его положение. Можно не рисовать, потом все прикрутим. Сейчас главное посчитать где находится каждый блок;
2. Рассчитать итоговый размер для `viewBox`.

Пусть сначала основные блоки `theme` ставятся в центре. К ним по бокам (по половине с одной стороны, по половине с другой, может быть нечетное число)  прикрепляются `module`. 

Размер всех блоков пусть будет константой (любой). 

Расстояние от основного блока по сторонам константа -- любая. 

![telegram-cloud-photo-size-2-5391180604097280580-y](https://user-images.githubusercontent.com/34986204/163852429-45493ccd-39ce-476b-8311-eecaf1f7438e.jpg)
![telegram-cloud-photo-size-2-5391180604097280581-y](https://user-images.githubusercontent.com/34986204/163852444-5f9924f0-caff-4fa9-a6c9-7ae787ad868d.jpg)
![telegram-cloud-photo-size-2-5391180604097280584-y](https://user-images.githubusercontent.com/34986204/163852466-77629f9b-a9bf-41f5-bdcc-6734eb8cef6a.jpg)

**Comment by denisSurkov** [comment]
Для удобства ширина может быть любой 

У чела с roadmap.sh стояла 1200 (удобно делить)

А вот высоту нужно посчитать после конфига

**Comment by denisSurkov** [comment]
На выходе еще может быть такой формат:

```json
[
  {
    "x": 600,
    "y": 200,
    "children": [
      {
        "x": 300,
        "y": 200
      }
    ]
  },
  {
    "x": 600,
    "y": 400,
    "children": [
      {
       "x": 300,
       "y": 400
      },
     {
        "x": 900,
        "y": 400
      }
    ]
  }
]
```

**Comment by artemijkurganov** [comment]
Решено? Можно закрывать?

**Comment by denisSurkov** [comment]
Да
