### ISSUE TITLE
Дизайн "собрать собственный путь"

### ISSUE THREAD

**Issue by denisSurkov** [denisSurkov/fiit-courses-vizualizator#9]
После 25 числа нам нужно будет сделать собственный путь:

![telegram-cloud-photo-size-2-5400026149372933920-y](https://user-images.githubusercontent.com/34986204/163853064-19100561-7f15-41b5-a2c7-97f8df0fd234.jpg)

**Comment by artemijkurganov** [comment]
На неделе 23-29 мая поработаю над этим дизайном в Figma

**Comment by artemijkurganov** [comment]
Дизайн того, как я вижу на данный момент составления своего пути, используя drag-and-drop, готов по той же ссылке:

https://www.figma.com/proto/WGF4bQoWjH0xPK7dlgOUH8/Design-for-fiit-courses-vizualizator?page-id=0%3A1&node-id=51%3A243&viewport=-123%2C-800%2C0.16&scaling=scale-down-width&starting-point-node-id=51%3A243

Ссылка "Составить свой путь" теперь ведёт на новую страницу.
При нажатии на прямоугольники с семестрами появляется боковое меню, откуда можно перетаскивать курсы

**Comment by denisSurkov** [comment]
@artemijkurganov , закрываем?

**Comment by artemijkurganov** [comment]
Закрываем
